services:
  postgres:
    container_name: postgres
    image: postgres:17
    networks:
      - movie
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5

  nats:
    container_name: nats
    image: nats:latest
    env_file:
      - .env
    networks:
      - movie
    ports:
      - "${NATS_PORT_1}:4222"
      - "${NATS_PORT_2}:8222"
    volumes:
      - ./nats/jetstream:/jetstream
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8222/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    command: ["-js", "-m", "8222"]

networks:
  movie:
    driver: bridge
